### ISSUE TITLE
Plugin is not compatible with vim-indent-guides

### ISSUE THREAD

**Issue by ElDeveloper** [itchyny/screensaver.vim#2]
If I have [vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides) enabled, screensaver won't be active on screen. The problem goes away if I disable indent-guides.

**Comment by itchyny** [comment]
Please disable the indent-guide plugin within the screensaver buffer.
```vim
let g:indent_guides_exclude_filetypes = ['screensaver']
```

**Comment by ElDeveloper** [comment]
Awesome, that works!
